/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhirsem2;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;

/**
 *
 * @author Corvoo
 */
public class transaksi extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    DefaultTableModel tabModel;
    private menu menuUtama;
    public long total;

    /**
     * Creates new form transaksi
     */
    public transaksi() {
        this(null);
        // initComponents();
        // koneksi DB = new koneksi();
        // DB.config();
        // con = DB.con;
        // stat = DB.stm;
        //
        // judul();
        // //tampilData("");
        // tampilComboBarang();
        // noFaktur();
    }

    public transaksi(menu menuUtama) {

        initComponents();

        this.menuUtama = menuUtama;

        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;

        judul();
        tampilData("");
        tampilComboBarang();
        noFaktur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idbeli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pilihanbarang = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        totalbeli = new javax.swing.JTextField();
        btnSelesai = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        hargabarang = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        idBarang = new javax.swing.JTextField();
        namabeli = new javax.swing.JTextField();
        tStok = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(174, 226, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("TRANSAKSI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID Pembeli");

        idbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbeliActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama Pembeli");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Barang");

        pilihanbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang" }));
        pilihanbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbarangActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Qty");

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Total Belanja");

        totalbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalbeliActionPerformed(evt);
            }
        });

        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        idBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idBarangActionPerformed(evt);
            }
        });

        namabeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namabeliActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(tblTransaksi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(idbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 96,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(namabeli)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                        .addComponent(totalbeli,
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(qty,
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(pilihanbarang,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                0, 95, Short.MAX_VALUE)
                                                                        .addComponent(btnHitung,
                                                                                javax.swing.GroupLayout.Alignment.LEADING))
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(43, 43, 43)
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                        .addComponent(tStok,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                112, Short.MAX_VALUE)
                                                                                        .addComponent(hargabarang))
                                                                                .addGap(34, 34, 34))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel1Layout.createSequentialGroup()
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                17, Short.MAX_VALUE)
                                                                                        .addComponent(btnSelesai)
                                                                                        .addGap(50, 50, 50)
                                                                                        .addComponent(btnBatal)))))
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addComponent(idBarang,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 81,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(41, 41, 41)
                                                                .addComponent(btnKembali)))))
                                .addContainerGap(45, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(237, 237, 237)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(idbeli, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(namabeli, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(pilihanbarang, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(hargabarang, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(idBarang, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tStok, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(totalbeli, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnHitung)
                                        .addComponent(btnSelesai)
                                        .addComponent(btnBatal)
                                        .addComponent(btnKembali))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalbeliActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_totalbeliActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_totalbeliActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_qtyActionPerformed

    private void pilihanbarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pilihanbarangActionPerformed
        // TODO add your handling code here:
        if (pilihanbarang.getSelectedItem().equals("Pilih Barang")) {
            idBarang.setText("");
            hargabarang.setText("");
        } else {
            try {
                stat = con.createStatement();
                rs = stat.executeQuery("SELECT idBarang, jumlahBarang FROM barang WHERE namaBarang ='"
                        + pilihanbarang.getSelectedItem() + "'");
                while (rs.next()) {
                    idBarang.setText(rs.getString("idBarang"));
                    tStok.setText(rs.getString("jumlahBarang"));

                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            try {
                stat = con.createStatement();
                rs = stat.executeQuery(
                        "SELECT hargaBarang FROM barang WHERE namaBarang ='" + pilihanbarang.getSelectedItem() + "'");
                DecimalFormatSymbols indo = new DecimalFormatSymbols();
                indo.setGroupingSeparator('.');
                DecimalFormat df = new DecimalFormat("#,###", indo);
                while (rs.next()) {
                    hargabarang.setText(df.format(rs.getDouble("hargaBarang")));
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }// GEN-LAST:event_pilihanbarangActionPerformed

    private void idbeliActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_idbeliActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_idbeliActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        if (idbeli.getText().equals("") || idBarang.getText().equals("") || pilihanbarang.getSelectedItem().equals("")
                || totalbeli.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Lengkapi Data", "Stroe Saya", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String idPem = idbeli.getText();
            String idbarang = idBarang.getText();
            String namapem = namabeli.getText();
            String nama = (String) pilihanbarang.getSelectedItem();
            String harga = hargabarang.getText().replace(".", "");
            String tqty = qty.getText();
            String jumlah = totalbeli.getText().replace(".", "");
            try {
                String sql = "INSERT INTO transaksi (idPem, idBarang, namapem, namaBarang, hargaBarang, qty, totalBelanja) VALUES (?,?,?,?,?,?,?)";

                try (java.sql.PreparedStatement p = con.prepareStatement(sql)) {
                    p.setString(1, idPem);
                    p.setString(2, idbarang);
                    p.setString(3, namapem);
                    p.setString(4, nama);
                    p.setString(5, harga);
                    p.setString(6, tqty);
                    p.setString(7, jumlah);
                    int baris = p.executeUpdate();

                    if (baris > 0) {
                        idBarang.setText("");
                        namabeli.setText("");
                        pilihanbarang.setSelectedItem("");
                        hargabarang.setText("");
                        qty.setText("");
                        totalbeli.setText("");
                        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan", "Elektronik",
                                JOptionPane.INFORMATION_MESSAGE);
                        noFaktur();
                        tampilData("");
                    } else {
                        JOptionPane.showMessageDialog(null, "Data Gagal Disimpan", "Elektronik",
                                JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi Error: " + e.getMessage(), "Elektronik",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }// GEN-LAST:event_btnSelesaiActionPerformed

    private void namabeliActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_namabeliActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_namabeliActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        batal();
    }// GEN-LAST:event_btnBatalActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        try {
            if (idbeli.getText().equals("") || pilihanbarang.getSelectedItem().equals("")
                    || hargabarang.getText().equals("") || qty.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Lengkapi Data", "Stroe Saya", JOptionPane.INFORMATION_MESSAGE);
                String a = qty.getText();
                int aa = Integer.parseInt(a);
                String b = tStok.getText();
                int bb = Integer.parseInt(b);
                if (aa > bb) {
                    JOptionPane.showMessageDialog(null, "Qty Melebihi Stok", "Stroe Saya",
                            JOptionPane.INFORMATION_MESSAGE);
                    qty.setText("");
                }
            } else {
                if (qty.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Isi Qty");
                } else {
                    int tqty, harga, jumlah;

                    tqty = Integer.parseInt(qty.getText().toString());
                    String hargaBersih = hargabarang.getText().replace(".", "");
                    harga = (int) Double.parseDouble(hargaBersih);
                    jumlah = tqty * harga;

                    DecimalFormatSymbols indo = new DecimalFormatSymbols();
                    indo.setGroupingSeparator('.');
                    DecimalFormat df = new DecimalFormat("#,###", indo);
                    totalbeli.setText(df.format(jumlah));

                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }// GEN-LAST:event_btnHitungActionPerformed

    private void idBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_idBarangActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_idBarangActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnKembaliActionPerformed
        int pilih = JOptionPane.showConfirmDialog(
                this,
                "Kembali ke Menu Utama?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

        if (pilih == JOptionPane.YES_OPTION) {

            if (menuUtama != null) {
                menuUtama.setLocationRelativeTo(this);
                menuUtama.setVisible(true);
            }

            dispose();
        }
    }// GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JTextField hargabarang;
    private javax.swing.JTextField idBarang;
    private javax.swing.JTextField idbeli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField namabeli;
    private javax.swing.JComboBox<String> pilihanbarang;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField tStok;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField totalbeli;

    // End of variables declaration//GEN-END:variables
    // private void judul() {
    // Object[] judul = {
    // "id Barang", "Nama Barang", "Harga Barang", "Qty", "Total Beli"
    // };
    //
    // }
    private void judul() {

        Object[] judul = {
                "ID Pembeli",
                "ID Barang",
                "Nama Pembeli",
                "Nama Barang",
                "Harga",
                "Qty",
                "Total"
        };

        tabModel = new DefaultTableModel(null, judul);
        tblTransaksi.setModel(tabModel);

    }

    public void batal() {
        pilihanbarang.setSelectedItem("");
        idBarang.setText("");
        hargabarang.setText("");
        qty.setText("");
        totalbeli.setText("");
    }

    private void tampilComboBarang() {
        try {
            stat = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = stat.executeQuery("SELECT namaBarang FROM barang WHERE jumlahBarang !='0'");
            while (rs.next()) {
                pilihanbarang.addItem(rs.getString("namaBarang"));
            }
            rs.last();
            int jumlahdata;
            jumlahdata = rs.getRow();
            rs.first();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void tampilData(String where) {
        try {
            stat = con.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.getDataVector();
            tabModel.fireTableDataChanged();
            rs = stat.executeQuery("SELECT * FROM transaksi" + where);

            DecimalFormatSymbols indo = new DecimalFormatSymbols();
            indo.setGroupingSeparator('.');
            DecimalFormat df = new DecimalFormat("#,###", indo);

            while (rs.next()) {
                Object[] data = {
                        rs.getString("idPem"),
                        rs.getString("idBarang"),
                        rs.getString("namapem"),
                        rs.getString("namaBarang"),
                        df.format(rs.getDouble("hargaBarang")),
                        rs.getString("qty"),
                        df.format(rs.getDouble("totalBelanja"))
                };
                tabModel.addRow(data);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    private void noFaktur() {
        try {
            stat = con.createStatement();
            rs = stat.executeQuery("SELECT * FROM transaksi ORDER by idPem desc");
            if (rs.next()) {
                String nofak = rs.getString("idPem").substring(1);
                String AN = "" + (Integer.parseInt(nofak) + 1);
                String nol = "";

                switch (AN.length()) {
                    case 1:
                        nol = "000";
                        break;
                    case 2:
                        nol = "00";
                        break;
                    case 3:
                        nol = "0";
                        break;
                    case 4:
                        nol = "";
                        break;
                }

                idbeli.setText("F" + nol + AN);
            } else {
                idbeli.setText("F0001");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

}
